apiVersion: v1
kind: Service
metadata:
  name: datainsights-zipkin-svc
spec:
  selector:
    app: datainsights-zipkin-endpoint
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9441
      nodePort: 30441
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datainsights-zipkin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datainsights-zipkin-endpoint
      env: prod
  template:
    metadata:
      labels:
        app: datainsights-zipkin-endpoint
        env: prod
    spec:
      containers:
        - name: datainsights-zipkin-endpoint
          image: 192.168.10.82:5555/datainsights-zipkin:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "384Mi"
              cpu: "200m"
          ports:
            - name: http-port
              containerPort: 9441
          envFrom:
            - configMapRef:
                name: spring-cloud-config
            - secretRef:
                name: spring-cloud-secret
          env:
            - name: HEAP_SIZE
              value: 384m
          volumeMounts:
            - name: log-volume
              mountPath: /var/datainsights-logs/datainsights-zipkin
          readinessProbe:
            tcpSocket:
              port: http-port
            initialDelaySeconds: 200
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http-port
            initialDelaySeconds: 200
            timeoutSeconds: 10
            periodSeconds: 5
      volumes:
        - name: log-volume
          hostPath:
            path: /var/datainsights-logs/datainsights-zipkin
            type: DirectoryOrCreate