---
apiVersion: v1
kind: Service
metadata:
  name: datainsights-upms-svc
spec:
  selector:
    app: datainsights-upms-endpoint
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30004
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datainsights-upms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datainsights-upms-endpoint
      env: prod
  template:
    metadata:
      labels:
        app: datainsights-upms-endpoint
        env: prod
    spec:
      containers:
        - name: datainsights-upms-endpoint
          image: 192.168.10.82:5555/datainsights-upms-biz:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "640Mi"
              cpu: "400m"
          envFrom:
            - configMapRef:
                name: spring-cloud-config
            - secretRef:
                name: spring-cloud-secret
          ports:
            - name: http-port
              containerPort: 4000
          env:
            - name: HEAP_SIZE
              value: 640m
            - name: WAIT_SERVICE
              value: datainsights-tx-manager-svc
          readinessProbe:
            httpGet:
              port: http-port
              path: /actuator/health
            initialDelaySeconds: 210
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: http-port
              path: /actuator/health
            initialDelaySeconds: 210
            periodSeconds: 5
          volumeMounts:
            - name: log-volume
              mountPath: /var/datainsights-logs/datainsights-upms-biz
      volumes:
        - name: log-volume
          hostPath:
            path: /private/var/datainsights-logs/datainsights-upms-biz
            type: DirectoryOrCreate
      initContainers:
        - name: init
          image: busybox
          env:
            - name: WAIT_SERVICE
              value: datainsights-tx-manager-svc
          command:
            - sh
            - "-c"
            - |
              until nc -w 2 -z $(WAIT_SERVICE) 80; do
                echo Waiting for $(WAIT_SERVICE) initialization to complete..
                sleep 10
              done
              echo $(WAIT_SERVICE) Initialization successful!