apiVersion: v1
kind: Service
metadata:
  name: datainsights-tx-manager-svc
spec:
  selector:
    app: datainsights-tx-manager-endpoint
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datainsights-tx-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datainsights-tx-manager-endpoint
      env: prod
  template:
    metadata:
      labels:
        app: datainsights-tx-manager-endpoint
        env: prod
    spec:
      containers:
        - name: datainsights-tx-manager-endpoint
          image: 192.168.10.82:5555/datainsights-tx-manager:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "740Mi"
              cpu: "400m"
          envFrom:
            - configMapRef:
                name: spring-cloud-config
            - secretRef:
                name: spring-cloud-secret
          env:
            - name: HEAP_SIZE
              value: 740m
            - name: SERVER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WAIT_SERVICE
              value: datainsights-register-svc
          ports:
            - name: http-port
              containerPort: 5004
          readinessProbe:
            httpGet:
              port: http-port
              path: /actuator/health
            initialDelaySeconds: 300
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: http-port
              path: /actuator/health
            initialDelaySeconds: 300
            periodSeconds: 5
          volumeMounts:
            - name: log-volume
              mountPath: /var/datainsights-logs/datainsights-tx-manager
      volumes:
        - name: log-volume
          hostPath:
            path: /private/var/datainsights-logs/datainsights-tx-manager
            type: DirectoryOrCreate
      initContainers:
        - name: init
          imagePullPolicy: Always
          image: busybox
          env:
            - name: WAIT_SERVICE
              value: datainsights-register-svc
          command:
            - sh
            - "-c"
            - |
              until nc -w 2 -z $(WAIT_SERVICE) 80; do
                echo Waiting for $(WAIT_SERVICE) initialization to complete..
                sleep 10
              done
              echo $(WAIT_SERVICE) Initialization successful!