apiVersion: v1
kind: Service
metadata:
  name: datainsights-gateway
spec:
  selector:
    app: datainsights-gateway-endpoint
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datainsights-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datainsights-gateway-endpoint
      env: prod
  template:
    metadata:
      labels:
        app: datainsights-gateway-endpoint
        env: prod
    spec:
      containers:
        - name: datainsights-gateway-endpoint
          image: 192.168.10.82:5555/datainsights-gateway
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - name: http-port
              containerPort: 9999
          envFrom:
            - configMapRef:
                name: spring-cloud-config
            - secretRef:
                name: spring-cloud-secret
          env:
            - name: HEAP_SIZE
              value: 256m
          readinessProbe:
            httpGet:
              port: http-port
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: http-port
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: log-volume
              mountPath: /var/datainsights-logs/datainsights-gateway
      volumes:
        - name: log-volume
          hostPath:
            path: /private/var/datainsights-logs/datainsights-gateway
            type: DirectoryOrCreate