apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    app: fileabeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      json.keys_under_root: true
      json.add_error_key: true
      paths:
        - /var/datainsights-logs/*/info.json

    output.kafka:
      enable: true
      hosts: ["${KAFKA_HOSTS}"]
      topic: "spring_cloud_log"
      partition.round_robin:
        reachable_only: true