apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    app: fileabeat
data:
  logstash.conf: |-
    input {
        tcp {
            port => 4560
            codec => json
            tags => ["4560"]
        }

        kafka {
            bootstrap_servers => "192.168.10.82:9092"
            codec => json
            topics => "spring_cloud_log"
            group_id => "logstash"
            tags => ["kafka"]
        }
    }

    filter {
        if "kafka" in [tags] or "4560" in [tags] {
            mutate {
                gsub => [
                        "log_level", " ", ""
                ]
                add_tag => [ "app-log"]
                remove_field => [ "@version", "ecs", "host", "input", "agent" ]
            }
            date {
                match => [ "timestamp", "yyyy-MM-dd HH:mm:ss.SSS||yyyy-MM-dd HH:mm:ss.SSSZ" ]
                timezone => "Asia/Shanghai"
                target => "@timestamp"
            }
        }
    }
    output {
        if "app-log" in [tags] {
            elasticsearch {
                hosts => ["192.168.10.125:9200"]
                index => "spring-cloud-%{service_name}-%{+YYYY.MM.dd}"
                manage_template => false
                document_type => "_doc"
                template_name => "spring_cloud_log_template"
                template_overwrite => true
            }
        }  else if "slow-log" in [tags] {
            elasticsearch {
                hosts => ["192.168.10.125:9200"]
                document_type => "doc"
                index => "mysql-slow-log-%{+YYYY.MM.dd}"
                manage_template => false
            }
        } else {
            stdout {codec => rubydebug}
        }
    }