{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "springcloud.serviceAccountName" . }}
  labels:
{{ include "springcloud.labels" . | indent 4 }}
{{- end -}}
